package ir.mapsa.jobinja.enums;

public enum Skills {
    ENGINEER,PAINTER,BAKER,NURSE,BUILDER,PROGRAMMER,TEACHER,MECHANIC,ASSISTANT,CHEF,ELECTRICIAN,BARBER,DRIVER,
    BODYGUARD,SINGER,WRITER,TYPIST
}
